---
title: "Annual PROD anaysis"
output: html_notebook
---


```{r}
# Load data and transform it 
cape = get(load("./CAPE_Baud_Rime.RData"))
srh = get(load("./SRH_Baud_Rime.RData"))
enso = get(load("./NINO34.RData"))
prod = sqrt(cape)*srh
```


```{r}
# Define variables
ppd <- 8 #point per day
years <- 37
months <- 12
data_size <- ppd*365*years #length(cape)
```

PROD DAY / MONTH / ANNUAL data:
```{r}

# Max of 8 points per day to 1 point per day and add date sequence 
td <- seq(as.Date("1979/01/01"), as.Date("2015/12/31"), "days")
td <- td[!grepl(x = td, pattern = "-02-29$")]
prod_day <- apply(matrix(prod,ncol=ppd,byrow=TRUE),1,max)
prod_day <- zoo(x = prod_day, order.by = td)

# Daily to monthly data taking max per month
tm <- seq(from=as.Date("1979/01/01"), to=as.Date("2015/12/01"), by = "month")
tm <- tm[!grepl(x = tm, pattern = "-02-29$")]
prod_month <- daily2monthly(prod_day, FUN=max, na.rm=TRUE) #prod max per month
length(prod_month)

# Daily to monthly data taking max per month
ta <- seq(from=as.Date("1979/01/01"), to=as.Date("2015/01/01"), "years")
#ta <- tm[!grepl(x = tm, pattern = "-02-29$")]
prod_annual <- monthly2annual(prod_month, FUN=max, na.rm=TRUE) #prod max per month
length(prod_annual)

# Plot daily/monthly maximum
plot(td, prod_day)
plot(tm, prod_month)
plot(ta, prod_annual, main="Annual raw data")

```

ENSO data:
```{r}
# Annual ENSO maxima:
enso_annual <- apply(matrix(enso,ncol=months,byrow=TRUE),1,max)
enso_annual <- zoo(x = enso_annual, order.by = ta)

plot(ta, enso_annual)
plot(enso_annual, prod_annual)

```

Estimate the Parameters of GEV with MLE for annual maxima:
```{r}
#print(c("SIM NB = ",month))
par(mfrow=c(1,1))
fit_gev = fgev(prod_annual)

#estimation of the parameters
parameters = fitted(fit_gev) 
print(c("parameters = ",parameters))

#std of the parameters (normal dist.)
std = std.errors(fit_gev)
print(c("standard error = ",std))
par(mfrow=c(2,2))
plot(fit_gev)

#Save plot
png(filename="C:/Users/Matthieu/Desktop/master1/Risk, Rare Event and Extremes/projectRisk-master/rapport/images/annual_gev_mle.png")
par(mfrow=c(2,2))
plot(fit_gev)
dev.off()

# Plot profile log likelihood for a better (asymmetric) std approximate
prof_log <- profile(fit_gev)
plot(prof_log)
plot(ta, prod_annual, main="Annual raw data")

#Save plot
png(filename="C:/Users/Matthieu/Desktop/master1/Risk, Rare Event and Extremes/projectRisk-master/rapport/images/annual_gev_prof_log_mle.png")
Years <- ta
par(mfrow=c(2,2))
plot(prof_log)
plot(Years, prod_annual, main="Annual raw data")
dev.off()
```


Question 2: relation of extremes with enso and or time, ratio and correlation:
```{r}
########################################################################
years_vec <- c(1979:2015)
enso_annual <- as.numeric(enso_annual)
# Check ratio stat with ENSO

#print(c("SIM NB = ",month))
#x_month = as.numeric(prod_monthly[, month])
fit_gev = fgev(prod_annual)
fit_gev_enso <-fgev(prod_annual,nsloc=enso_annual)
ratio <- fit_gev$dev-fit_gev_enso$dev
p <- 1-pchisq(ratio,1)
#print(c("ratio = ",ratio))
print(c("p-value = ",p))
par(mfrow=c(1,2))
plot(years_vec,prod_annual)
plot(years_vec,enso_annual)

# Check ratio stat with TIME
#print(c("SIM NB = ",month))
#x_month = as.numeric(prod_monthly[, month])
fit_gev = fgev(prod_annual)
fit_gev_time <-fgev(prod_annual,nsloc=c(1:37))
ratio <- fit_gev$dev-fit_gev_time$dev
p <- 1-pchisq(ratio,1)
#print(c("ratio = ",ratio))
print(c("p-value = ",p))
par(mfrow=c(1,2))
plot(years_vec,prod_annual)
plot(years_vec,enso_annual)


# Check correlation with ENSO

#print(c("SIM NB = ",month))
#x_month <- as.numeric(prod_monthly[, month])
mat1 <- cbind(prod_annual,enso_annual)
plot(mat1)
corr <- cor(mat1)
print(c("Correlation = ",corr[2]))
#mat2 <- cbind(x_month,abs(enso[seq(from = month, to = 444, by = 12)]))
#plot(mat2)
#corr_abs <- cor(mat2)
#print(c("Correlation ABSOLU= ",corr_abs))

```

MArkiv Chain Monte Carlo model:
!!!Choose parameters correctly!!!
```{r}
#######################################################
#MCMC
init <- c(5000,1000,0)
mat = diag(c(1e11,1e8,1e8))
#mat = diag(c(1e8,1e5,1e5))
pn = prior.norm(mean=c(0,0,0),cov=mat) # normal distribution

psd = c(800,0.10,0.12) # sd for proposal dist (normal dist)
# initial value, prior distribution: normal, likelihood: gev, psd: 
#post = posterior(5000,init=init,prior=pn,lh="gev",data=x_monthly,psd=psd)
post = posterior(5000,init=init,prior=pn,lh="gev",data=prod_annual,psd=psd)

#mc = mcmc(post[-c(1:300),])
mc = mcmc(post)
plot(mc)
attr(mc,"ar")

#V2 params
MCMC2<-mcmc(post[-c(1:500),])
acf(MCMC2)

MCMC3<-mcmc(post[500 + 9*c(1:500),])
acf(MCMC3)
apply(MCMC3,2,mean)
apply(MCMC3,2,sd)

#Old one
#MCMC2<-mcmc(post[-c(1:300),])
#acf(MCMC2)

#MCMC3<-mcmc(post[500 + 7.5*c(1:337),])
#acf(MCMC3)
#apply(MCMC3,2,mean)
#apply(MCMC3,2,sd)

# Return level MCMC
hist(as.numeric(MCMC3[,3]),nclass=20,prob=T,main="Histogram of xi",xlab="xi")
u.10<-mc.quant(MCMC3,p=0.9,lh="gev")
u.100<-mc.quant(MCMC3,p=0.99,lh="gev")
hist(u.10,nclass=20,prob=T,xlab="10-year return level")
hist(u.100,nclass=20,prob=T,xlab="100-year return level")

print(c("rl10 MCMC = ",u.10))
print(c("rl100 MCMC = ",u.100))
```














```
























